version: "3.7"
services:
  postgres_db:
    image: postgres:latest
    container_name: database
    restart: always
    networks:
      - blog
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

networks:
  blog:
    driver: bridge